### PR TITLE
Remove context.succeed/callback calls from savestate

### PR DESCRIPTION
**Pull request by knowlsie**
This makes `this.emit(':saveState')` perform as expected, without calling anything that ends the session unless there's an error. This should resolve https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/88. Note that no changes to documentation really need to be made, as actually it now performs as it's documented, without sending off a response. Let me know if you need any further changes - I'm fairly confident it now has the expected behaviour, but not totally sure. 🙂

### CODE REVIEW

**Comment by bclement-amazon** [comment]
Testing this now...

**Comment by coltonw** [comment]
I believe this pull request introduced #164

**Comment by t2048** [comment]
Pretty sure this change in logic has created a bug where the lambda returns before writes to DynamoDB have finished. I added logging to the response.js ':saveState' code as follows:

                console.log('saving state');
                attributesHelper.set(this.handler.dynamoDBTableName, userId, this.attributes, (err) => {
                    console.log('state saved');

Look at execution in Cloudwatch and you can see the 'state saved' message often is not logged until after the requestId has logged its 'END' event.

2017-08-30T08:46:14.782Z	adf4560c-8d5f-11e7-8824-411bdd375215	saving state
END RequestId: adf4560c-8d5f-11e7-8824-411bdd375215
START RequestId: b4a04085-8d5f-11e7-8d9c-dfd1ecc96a8e Version: $LATEST
2017-08-30T08:46:25.005Z	adf4560c-8d5f-11e7-8824-411bdd375215	state saved

**Comment by tgies** [comment]
Piling on -- wrote over on #164 about why this introduced #164.

**Pull request merged**
