### PR TITLE
Allow state to be reset to empty string

### PR DESCRIPTION
**Pull request by knowlsie**
The current `if(this.handler.state)` doesn't allow the state to be reset to an empty string (''), as an empty string is falsey, so evaluates to false. 

The problem with this is that an empty string is the default state that Alexa uses on opening a new session, so it's extremely useful to be able to return to this state. It's especially useful for the built-in AMAZON.StartOverIntent. 

I've been using this small fix for several days with no problems, and it very simply allows the state to be reset to an empty string.

### CODE REVIEW

**Comment by cspinillo** [comment]
Have you tried not setting that "newSession" handler and just setting the default session to a state? If so, what happened?

**Comment by knowlsie** [comment]
Yo, I did previously try what you suggest (I'm not using NewSession anyway in my skill), and I *believe* it won't work without at least one "stateless" set of handlers; I've not been able to get it to run without that basic set of handlers. I also know the SDK code very well at this point, and logically I don't think it *should* work without those handlers (unless you edit the SDK itself.) There are easy ways around this without changing the SDK code if you're interested. If you just manually change the sessionAttributes at the same time as the state, it can reset:

```
  this.handler.state = "";
  this.handler.response.sessionAttributes['STATE'] = "";
  ```

Alternatively, you can very quickly have a whole set of handlers for restarting the session, though that does rely on repeating your code. 

It's possible that this pull may not be accepted due an issue with DynamoDB not storing empty strings, but I really do think this is something they should consider fixing because it's confusing for beginners, and that's who this SDK is designed for, honestly.

**Comment by mattrayner** [comment]
This is currently a blocker for me and would love to see this implemented

**Comment by mattrayner** [comment]
@bclement-amazon do you have a public list of features that are being included in future releases? Just to get an idea of timescales for bugs like this :)

**Comment by knowlsie** [comment]
I posted a fix above if you need it. Instead of:
```
this.handler.state = "";
```
Put:
```
this.handler.state = "";
this.handler.response.sessionAttributes['STATE'] = "";
```

**Comment by mattrayner** [comment]
Hi @knowlsie - unfortunately that doesn't fix my issue - in the end I had to create an additional state (I called it '_NULL')

I have two logical branches and needed to persist into DynamoDB the default state, otherwise asking for help etc gives an incorrect contextual response (if that makes sense)

**Comment by tianrenz** [comment]
Hi, 

Just checking if this PR is still active. It seems there's some merge conflict in this PR. If you could resolve those, we would be happy to review it. 

Regards

**Pull request closed without merging**
