### PR TITLE
Expose the ability to inject a custom DynamoDB client

### PR DESCRIPTION
**Pull request by daemonsy**
- Imagined use case: TDD using dynamoDB local
- Set your own client using `<Alexa Handler>.dynamoDBClient`
- If not set, it uses the default client to keep things convention over configuration

### CODE REVIEW

**Comment by abhilash1in** [comment]
Does the official SDK support `alexa.dynamoDBClient`?

**Comment by mblaya** [comment]
It would be great to have the dynamo handler available.
I am trying to use a separate table for some application data but I cannot (or I don't know how to) manage it. After a couple of days of tries and searches, I got here.
Any luck anybody finding a workaround ?

**Comment by neilsmind** [comment]
@daemonsy Did this go anywhere somewhere else? It looks like the PR now has conflicts. Would love to be able to test locally using mocha but issue #139 was closed two weeks ago by @Amazon-tianrenz

**Comment by daemonsy** [comment]
@neilsmind when I made the PR originally, it worked fully for testing with any framework. Just allowed you to stub away the dynamo client. But so much time passed now, I'm not sure. 

Happy to resolve the conflicts and make it work again, but would like to know Amazon's stance on the issue / PR. Haven't heard anything from the maintainers yet.

**Comment by neilsmind** [comment]
@daemonsy Thanks for the quick reply! I just heard from @Amazon-tianrenz on #134 with the following (when asked if they wanted help getting this PR's conflicts resolved):
> I've created action item on internal backlog to track #139 and labeled it as "feature request". Please move to #139 for further discussion on local DynamoDB testing.
> We are constantly reviewing PRs so it would be great if you can update the PR #140 with the latest SDK.

So it would seem that they're aware of the issue (#139) and if we can get the PR cleaned up, we may be able to get it reviewed / merged(?). I have a thought / question on the PR but for context, I'll add as a PR review.

**Comment by ultradian** [comment]
Hi.  I'm still new to the process here, so any comments about my comments or documentation is appreciated.  I continued the work of @daemonsy and just submitted a PR #242 which resolved the conflicts and also edited `alexa.js` to allow definition of a local dynamoDB client like:

    alexa.dynamoDBClient = new aws.DynamoDB({
        accessKeyId: 'AKID',
        secretAccessKey: 'SECRET',
        region: "us-east-1",
        endpoint: "http://localhost:8000",
        apiVersion: '2012-08-10'
    });

I have mainly been using the [`testflow.js`](https://github.com/alexa/alexa-cookbook/tree/master/testing/TestFlow) program from the alexa-cookbook, so not really doing any true TDD and am unable to say if this works with any other frameworks.  I hope this helps move the process forward and again appreciate any information about how I can better shape my contributions to be the most effective.

**Comment by daemonsy** [comment]
Hey @ultradian sorry for the radio silence, didn't see the notifications. I updated the PR and resolved the merge conflicts, but my WIP tests in an alexa skill isn't passing. Will investigate.

**Comment by ultradian** [comment]
Hi @daemonsy.  No worries re: speed of response.  You are a lot faster than many!  I just noticed that #139 is still open, so am trying to move things there.  Let me know if you think my minor changes in PR #242 should merge with yours or vice versa to clean some stuff out.

**Comment by Amazon-tianrenz** [comment]
Hi all, 
Thanks for everyone's discussion on this thread. I'll throw in some of my suggestions here too. 

Currently behavior is that ``AttributesHelper`` spawns a new ``aws.DynamoDB.DocumentClient`` in every ``set`` and ``get`` call.  So try to injecting a new DynamoDB Client seems a bit redundant. If the goal here is to enable choice for configuring the DBClient for Local testing or switching regional endpoint, a simpler fix (from my point of view) would be to inject a DynamoDB configuration JSON and pass that into the ``AttributesHelper``. 

This way, developers using the SDK can avoid the boilerplate code to introduce a new dependency (aws-sdk) and actually create the DB client. 

We have a task currently in backlog to add this feature. It will be enabled in future updates. Stay tuned! 

Regards

**Comment by ultradian** [comment]
@Amazon-tianrenz That sounds like a great idea.  I'm looking forward to seeing it implemented. When that happens, how is the public usually notified?  Is it just here on Github or it get pushed into the documentation at https://developer.amazon.com/docs/custom-skills ?

**Comment by Amazon-tianrenz** [comment]
Hi all, 

Thanks for everyone's attention on this issue. The latest release has enabled developer to inject their own dynamoDB client into SDK. 

Regards

**Pull request closed without merging**
