### PR TITLE
Full ECMAScript6 integration & basic JSDoc add

### PR DESCRIPTION
**Pull request by linslin**

### CODE REVIEW

**Comment by feedm3** [comment]
Good idea, but I think the variables should all be declared with `const` by default and not `let`. Also, whats the benefit of blank JSDoc?

**Comment by linslin** [comment]
Hi @feedm3,

I added const where it is needed. Declaring all vars with `const` will break the application. What do you mean wih "blank" JSDoc, its not blank there is just no description. The benefit tis the same but my english is not that well so I did not wrote down descriptions.

**Comment by knowlsie** [comment]
You should cover the other files too, not just Alexa.js. I'm also not sure whether the team will be happy to pull 'empty' JSDocs, as the SDK generally seems to be a pretty strictly maintained affair. I'm not them though, so I want speak for them.

**Comment by linslin** [comment]
@knowlsie what is a empty JSDoc? Yea, I will cover the other files to and clean up your messy codes ;-)

**Comment by feedm3** [comment]
Empty JSDoc is JSDoc without description. Documentation without description it's just repetition of the function arguments and therefore I don't see any benefit.

Having said that I see benefit in JSDoc with description, I also think a good api should document all public functions (but this should be done in another merge request).

**Comment by knowlsie** [comment]
@linslin, I totally agree on the benefits of JSDoc, but I'm just saying I think the team will want them to have an actual description before they pull in. (Also, I'm not even a contributor to this project yet; this is not my code!)

**Comment by linslin** [comment]
> Empty JSDoc is JSDoc without description. Documentation without description it's just repetition of the function arguments and therefore I don't see any benefit.

This is just wrong. I realy dont agree with your statement "blank JSDoc". The changes I made currently gives me a benefit while developening:

- code autocomplete in IDE
- code following in IDE
- type check in IDE
- extend class helping

The description is also nice to have. I just said, my english is not that well. So I will not write down those descriptions. I see no problem with merging this request and adding the descriptions later. IMO this pull request is the first step into a "more well formed application". Please tell me if you going to merge this, so I will add the ECMAScript6 integration and JSDoc's for the other files.

Thanks

**Comment by knowlsie** [comment]
(I don't think either of us are maintainers, so we can't merge this.) Without speaking for @feedm3, I'm certainly not claiming empty JSDocs are useless, I'm claiming that fully described JSDocs are better. I suspect that fully described JSDocs are what the maintainers will want.

**Comment by linslin** [comment]
@knowlsie Thats what i told. Descriptions are nice to have but I'm not able to add them. I did not say "descriptions" are useless. The benefit of this pull request is great. I don't know why talk about missing descriptions which can be easily added later.

**Comment by michaelborchardt** [comment]
@knowlsie @linslin 

I'm sure they want to add documentation, maintainers are just following proper agile manifesto protocol.
"Working software over comprehensive documentation"

**Pull request closed without merging**
