### PR TITLE
add abstract handler for standard use cases

### PR DESCRIPTION
**Pull request by hoegertn**
## Description
This PR adds abstract handler classes for standard use cases like IntentRequests and AudioPlayer Events

## Motivation and Context
With this classes, it is easier to implement default handler.

## Testing
There are new spec tests for the added handlers

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## License
- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by hoegertn** [comment]
I agree, that the SDK should not contain detailed implementations of features. But imho these handlers are needed by nearly every skill and are very generic. This just reduces the code needed for default handlers like it was possible with the old SDK. Putting it in a separate npm package is not really helpful as it is meant to ease development and not make it more complex by having to know to add several other packages.

I think SDKs should always provide some easy way to do default things and be able to be highly complex in other cases. But having only the complex way might scare developers.

**Comment by tianrenz** [comment]
The implementation here is not generic enough. Consider the following example: 
If `AudioPlayer` interface adds a new type of requests,(for example: `AudioPlayer.PlayBackStatusUpdate`), the existing `AudioPlayerRequestHandler` will not be able to support that. Even if we add another abstract function to the interface, it will be a breaking change for developers who has already extended the handler as they will have to implement the new abstract function. The core SDK packages needs to be easily extensible without having to introduce breaking changes.

**Comment by hoegertn** [comment]
And what about the `NamedIntentRequestHandler`? If you have problems with the AudioPlayer one I can split it and we discuss it separately. For me, the `NamedIntentRequestHandler` is much more important. I could live with having an extra package for AudioPlayer stuff.

**Comment by hoegertn** [comment]
IMHO SDK should also contain code that most of the developers will need to avoid code duplication and bugs due to reimplementing stuff. But I understand that you focus on extensibility and a very generic approach. So instead of adding more PRs I think I will start an add-on package as we would have the same discussion for nearly all of my upcoming PRs.

Thanks for your time.

**Comment by tianrenz** [comment]
Thanks so much! I look forward to your package. We are actively searching for solutions that will improve usability while pertaining extensibility. Thanks for providing valuable feedback!

**Comment by hoegertn** [comment]
I implemented it in https://www.npmjs.com/package/ask-sdk-addon

**Pull request closed without merging**
